# -*- mode: ruby -*-
# vi: set ft=ruby 

Vagrant.configure("2") do |config|
  #Maquina Wordpress
  
  config.vm.define "wp" do |wp|
    wp.vm.box = "ubuntu/focal64"
    wp.vm.hostname = "WP"
    wp.vm.provision "shell", path: 'discoswp.sh'
    wp.vm.provision "shell", path: 'servicios.sh'
    wp.vm.box_check_update = false
    wp.vm.network "forwarded_port", guest: 80, host: 8080
    wp.vm.network "private_network", ip: "192.168.2.3", netmask: "24", nic_type: "virtio", virtualbox__intnet: "funko"
    wp.vm.provider "virtualbox" do |v|
      v.name = "WP"
      v.memory = 1024
      v.cpus = 1
      file_to_disk1 = "extradiskWP.vmdk"
      unless File.exist?(file_to_disk1)
        v.customize [ "createmedium", "disk", "--filename", "extradiskWP.vmdk", "--format", "vmdk", "--size", 1024 * 10 ]
      end
      v.customize [ "storageattach", "WP" , "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", file_to_disk1]
     
    
    end
 end
  #Maquina ELK
  config.vm.define "elk" do |elk|
   elk.vm.box = "ubuntu/focal64"
    elk.vm.hostname = "elk"
    elk.vm.provision "shell", path: 'discoselk.sh'
    elk.vm.provision "shell", path: 'stackelk.sh'
    elk.vm.box_check_update = false
    elk.vm.network "forwarded_port", guest: 9200, host: 9200
    elk.vm.network "forwarded_port", guest: 80, host: 81
    elk.vm.network "private_network", ip: "192.168.2.2", netmask: "24", nic_type: "virtio", virtualbox__intnet: "funko"
    elk.vm.provider "virtualbox" do |v|
     v.memory = 4096
     v.cpus = 1
     v.name = "ELK"
     file_to_disk2 = "extradiskelk.vmdk"
     unless File.exist?(file_to_disk2)
       v.customize [ "createmedium", "disk", "--filename", "extradiskelk.vmdk", "--format", "vmdk", "--size", 1024 * 10 ]
     end
     v.customize [ "storageattach", "ELK" , "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", file_to_disk2]
    end
  end
end
